// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "post": {
                "summary": "Register new or sign in old user using Google OAuth2.0",
                "parameters": [
                    {
                        "description": "Google OAuth request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.GoogleOAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "summary": "Register new user and return auth data",
                "parameters": [
                    {
                        "description": "Create user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "summary": "Sign in to user account and return auth data",
                "parameters": [
                    {
                        "description": "Sign in request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/quest": {
            "get": {
                "summary": "Get many quests sorted by start time and finished status",
                "parameters": [
                    {
                        "maxLength": 3,
                        "minLength": 0,
                        "type": "array",
                        "items": {
                            "enum": [
                                "all",
                                "registered",
                                "owned"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Fields to return",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of quests to return for each field",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page ID to return. Mutually exclusive to multiple fields",
                        "name": "page_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quests.Quests"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "summary": "Create new quest",
                "parameters": [
                    {
                        "description": "Main quest information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.CreateQuestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Quest"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/quest/{id}/task-groups/bulk": {
            "patch": {
                "summary": "Patch task groups by creating new ones, delete, update and reorder all ones. Returns all exising task groups.",
                "parameters": [
                    {
                        "description": "Requests to delete/create/update task groups",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.TaskGroupsBulkUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.TaskGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/quest/{quest_id}": {
            "get": {
                "summary": "Get quest by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Quest"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "summary": "Update main quest information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quest information to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.UpdateQuestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Quest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            },
            "delete": {
                "summary": "Delete quest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/quest/{quest_id}/teams": {
            "post": {
                "summary": "Create new team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Desired team information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teams.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/teams/join/{invite_path}": {
            "get": {
                "summary": "Join team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team invite url param",
                        "name": "invite_path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/user/{user_id}": {
            "get": {
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.User"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "summary": "Update user public data such as username or avatar and returns new auth data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Public data to set for user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdatePublicDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    }
                }
            },
            "delete": {
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/user/{user_id}/password": {
            "post": {
                "summary": "Update user password",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Old and new password",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdatePasswordRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.User"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.GoogleOAuthRequest": {
            "type": "object",
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "auth.Response": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/storage.User"
                }
            }
        },
        "auth.SignInRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "quests.PaginatedQuestsResponse": {
            "type": "object",
            "properties": {
                "next_page_id": {
                    "type": "string"
                },
                "quests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.Quest"
                    }
                }
            }
        },
        "quests.Quests": {
            "type": "object",
            "properties": {
                "all": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                },
                "owned": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                },
                "registered": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                }
            }
        },
        "storage.AccessType": {
            "type": "string",
            "enum": [
                "public",
                "link_only"
            ],
            "x-enum-varnames": [
                "AccessPublic",
                "AccessLinkOnly"
            ]
        },
        "storage.CreateQuestRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "storage.CreateTaskGroupRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                }
            }
        },
        "storage.CreateUserRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://api.dicebear.com/7.x/thumbs/svg"
                },
                "password": {
                    "type": "string",
                    "example": "12345"
                },
                "username": {
                    "type": "string",
                    "example": "svayp11"
                }
            }
        },
        "storage.DeleteTaskGroupRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "storage.Quest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "creator": {
                    "$ref": "#/definitions/storage.User"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "storage.TaskGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "orderIdx": {
                    "type": "integer"
                },
                "pubTime": {
                    "type": "string"
                },
                "quest": {
                    "$ref": "#/definitions/storage.Quest"
                }
            }
        },
        "storage.TaskGroupsBulkUpdateRequest": {
            "type": "object",
            "properties": {
                "create": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.CreateTaskGroupRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.DeleteTaskGroupRequest"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.UpdateTaskGroupRequest"
                    }
                }
            }
        },
        "storage.Team": {
            "type": "object",
            "properties": {
                "captain": {
                    "$ref": "#/definitions/storage.User"
                },
                "id": {
                    "type": "string"
                },
                "invite_link": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.User"
                    }
                },
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "storage.UpdateQuestRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "creator_name": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "storage.UpdateTaskGroupRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                }
            }
        },
        "storage.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "teams.CreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "user.UpdatePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "user.UpdatePublicDataRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
