// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/google": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Register new or sign in old user using Google OAuth2.0",
                "parameters": [
                    {
                        "description": "Google OAuth request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/google.OAuthRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Register new user and return auth data",
                "parameters": [
                    {
                        "description": "Create user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.CreateUserRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/auth/sign-in": {
            "post": {
                "tags": [
                    "Auth"
                ],
                "summary": "Sign in to user account and return auth data",
                "parameters": [
                    {
                        "description": "Sign in request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/auth.SignInRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/quest": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Get many quests sorted by start time and finished status",
                "parameters": [
                    {
                        "maxLength": 3,
                        "minLength": 0,
                        "type": "array",
                        "items": {
                            "enum": [
                                "all",
                                "registered",
                                "owned"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "csv",
                        "description": "Fields to return",
                        "name": "fields",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Number of quests to return for each field",
                        "name": "page_size",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Page ID to return. Mutually exclusive to multiple fields",
                        "name": "page_id",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quests.Quests"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Create new quest",
                "parameters": [
                    {
                        "description": "Main quest information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.CreateQuestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Quest"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            }
        },
        "/quest/{id}/answer": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "PlayMode"
                ],
                "summary": "Answer task in play-mode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Answer data",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/play.TryAnswerRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/game.TryAnswerResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/quest/{id}/hint": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "PlayMode"
                ],
                "summary": "Take hint for task in play-mode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Take hint request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/play.TakeHintRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Hint"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/quest/{id}/play": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "PlayMode"
                ],
                "summary": "Get task groups with tasks for play-mode",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/game.AnswerDataResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/quest/{id}/table": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "PlayMode"
                ],
                "summary": "Get leaderboard table during quest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/game.TeamResults"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/quest/{id}/task-groups": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "TaskGroups"
                ],
                "summary": "Get task groups with tasks for quest creator",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/taskgroups.GetResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "TaskGroups"
                ],
                "summary": "Create task groups and tasks. All previously created task groups and tasks would be deleted and overridden.",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "All task groups with inner tasks to create",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/requests.CreateFullRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/requests.CreateFullResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/quest/{id}/task-groups/bulk": {
            "patch": {
                "tags": [
                    "TaskGroups"
                ],
                "summary": "[WIP] Patch task groups by creating new ones, delete, update and reorder all ones. Returns all exising task groups.",
                "parameters": [
                    {
                        "description": "Requests to delete/create/update task groups",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.TaskGroupsBulkUpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.TaskGroup"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    }
                }
            }
        },
        "/quest/{quest_id}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Get quest by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quest.TeamQuestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Update main quest information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Quest information to update",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/storage.UpdateQuestRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Quest"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "415": {
                        "description": "Unsupported Media Type"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Quests"
                ],
                "summary": "Delete quest",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/quest/{quest_id}/teams": {
            "get": {
                "tags": [
                    "Teams"
                ],
                "summary": "Get all teams by quest id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest id",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/storage.Team"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Create new team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Quest ID",
                        "name": "quest_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Desired team information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teams.CreateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/teams/join/{invite_path}": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Join team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team invite url param",
                        "name": "invite_path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "406": {
                        "description": "Not Acceptable"
                    }
                }
            }
        },
        "/teams/join/{invite_path}/quest": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Get quest by its team invite path",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team invite path",
                        "name": "invite_path",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/quest.TeamQuestResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/teams/{team_id}": {
            "get": {
                "tags": [
                    "Teams"
                ],
                "summary": "Get team by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Change team information",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New information",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teams.UpdateRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Delete team by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/teams/{team_id}/captain": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Change team captain",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Change captain request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teams.ChangeLeaderRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/teams/{team_id}/leave": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Leave the team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "New captain (if leader leaves)",
                        "name": "new_captain",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/teams/{team_id}/{member_id}": {
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Teams"
                ],
                "summary": "Remove member from team",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Team id",
                        "name": "team_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member id",
                        "name": "member_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.Team"
                        }
                    },
                    "400": {
                        "description": "Bad Request"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        },
        "/user/{user_id}": {
            "get": {
                "tags": [
                    "Users"
                ],
                "summary": "Get user by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/storage.User"
                        }
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Update user public data such as username or avatar and returns new auth data",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Public data to set for user",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/user.UpdatePublicDataRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/auth.Response"
                        }
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    },
                    "422": {
                        "description": "Unprocessable Entity"
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "tags": [
                    "Users"
                ],
                "summary": "Delete user account",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "401": {
                        "description": "Unauthorized"
                    },
                    "403": {
                        "description": "Forbidden"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    },
    "definitions": {
        "auth.Response": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/storage.User"
                }
            }
        },
        "auth.SignInRequest": {
            "type": "object",
            "properties": {
                "password": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "game.AnswerDataResponse": {
            "type": "object",
            "properties": {
                "quest": {
                    "$ref": "#/definitions/storage.Quest"
                },
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.AnswerTaskGroup"
                    }
                },
                "team": {
                    "$ref": "#/definitions/storage.Team"
                }
            }
        },
        "game.AnswerTask": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "boolean"
                },
                "answer": {
                    "type": "string"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.AnswerTaskHint"
                    }
                },
                "id": {
                    "type": "string"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "verification_type": {
                    "enum": [
                        "auto",
                        "manual"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.VerificationType"
                        }
                    ]
                }
            }
        },
        "game.AnswerTaskGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.AnswerTask"
                    }
                }
            }
        },
        "game.AnswerTaskHint": {
            "type": "object",
            "properties": {
                "taken": {
                    "type": "boolean"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "game.TaskGroupResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.TaskResult"
                    }
                }
            }
        },
        "game.TaskResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "game.TeamResult": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.TaskGroupResult"
                    }
                },
                "total_score": {
                    "type": "integer"
                }
            }
        },
        "game.TeamResults": {
            "type": "object",
            "properties": {
                "results": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/game.TeamResult"
                    }
                }
            }
        },
        "game.TryAnswerResponse": {
            "type": "object",
            "properties": {
                "accepted": {
                    "type": "boolean"
                },
                "score": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "google.OAuthRequest": {
            "type": "object",
            "properties": {
                "id_token": {
                    "type": "string"
                }
            }
        },
        "play.TakeHintRequest": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "task_id": {
                    "type": "string"
                }
            }
        },
        "play.TryAnswerRequest": {
            "type": "object",
            "properties": {
                "taskID": {
                    "type": "string"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "quest.TeamQuestResponse": {
            "type": "object",
            "properties": {
                "quest": {
                    "$ref": "#/definitions/storage.Quest"
                },
                "team": {
                    "$ref": "#/definitions/storage.Team"
                }
            }
        },
        "quests.PaginatedQuestsResponse": {
            "type": "object",
            "properties": {
                "next_page_id": {
                    "type": "string"
                },
                "quests": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.Quest"
                    }
                }
            }
        },
        "quests.Quests": {
            "type": "object",
            "properties": {
                "all": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                },
                "owned": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                },
                "registered": {
                    "$ref": "#/definitions/quests.PaginatedQuestsResponse"
                }
            }
        },
        "requests.CreateFullRequest": {
            "type": "object",
            "properties": {
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.CreateRequest"
                    }
                }
            }
        },
        "requests.CreateFullResponse": {
            "type": "object",
            "properties": {
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.TaskGroup"
                    }
                }
            }
        },
        "requests.CreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "pub_time": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/requests.CreateTaskRequest"
                    }
                }
            }
        },
        "requests.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "correct_answers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "type": "string",
                        "maxLength": 3
                    }
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "pub_time": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "verification": {
                    "enum": [
                        "auto",
                        "manual"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.VerificationType"
                        }
                    ]
                }
            }
        },
        "storage.AccessType": {
            "type": "string",
            "enum": [
                "public",
                "link_only"
            ],
            "x-enum-varnames": [
                "AccessPublic",
                "AccessLinkOnly"
            ]
        },
        "storage.CreateQuestRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string",
                    "example": "2024-04-21T14:00:00+05:00"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string",
                    "example": "2024-04-14T12:00:00+05:00"
                },
                "start_time": {
                    "type": "string",
                    "example": "2024-04-14T14:00:00+05:00"
                }
            }
        },
        "storage.CreateTaskGroupRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.CreateTaskRequest"
                    }
                }
            }
        },
        "storage.CreateTaskRequest": {
            "type": "object",
            "properties": {
                "correct_answers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "group_id": {
                    "type": "string"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "verification": {
                    "$ref": "#/definitions/storage.VerificationType"
                }
            }
        },
        "storage.CreateUserRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://api.dicebear.com/7.x/thumbs/svg"
                },
                "password": {
                    "type": "string",
                    "example": "12345"
                },
                "username": {
                    "type": "string",
                    "example": "svayp11"
                }
            }
        },
        "storage.DeleteTaskGroupRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "storage.DeleteTaskRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "storage.Hint": {
            "type": "object",
            "properties": {
                "index": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        },
        "storage.Quest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "creator": {
                    "$ref": "#/definitions/storage.User"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string",
                    "example": "2024-04-21T14:00:00+05:00"
                },
                "id": {
                    "type": "string"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string",
                    "example": "2024-04-14T12:00:00+05:00"
                },
                "start_time": {
                    "type": "string",
                    "example": "2024-04-14T14:00:00+05:00"
                },
                "status": {
                    "type": "string",
                    "enum": [
                        "ON_REGISTRATION",
                        "REGISTRATION_DONE",
                        "RUNNING",
                        "WAIT_RESULTS",
                        "FINISHED"
                    ]
                }
            }
        },
        "storage.Task": {
            "type": "object",
            "properties": {
                "correct_answers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "verification_type": {
                    "enum": [
                        "auto",
                        "manual"
                    ],
                    "allOf": [
                        {
                            "$ref": "#/definitions/storage.VerificationType"
                        }
                    ]
                }
            }
        },
        "storage.TaskGroup": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "tasks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.Task"
                    }
                }
            }
        },
        "storage.TaskGroupsBulkUpdateRequest": {
            "type": "object",
            "properties": {
                "create": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.CreateTaskGroupRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.DeleteTaskGroupRequest"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.UpdateTaskGroupRequest"
                    }
                }
            }
        },
        "storage.TasksBulkUpdateRequest": {
            "type": "object",
            "properties": {
                "create": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.CreateTaskRequest"
                    }
                },
                "delete": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.DeleteTaskRequest"
                    }
                },
                "update": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.UpdateTaskRequest"
                    }
                }
            }
        },
        "storage.Team": {
            "type": "object",
            "properties": {
                "captain": {
                    "$ref": "#/definitions/storage.User"
                },
                "id": {
                    "type": "string"
                },
                "invite_link": {
                    "type": "string"
                },
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.User"
                    }
                },
                "name": {
                    "type": "string"
                },
                "score": {
                    "type": "integer"
                }
            }
        },
        "storage.UpdateQuestRequest": {
            "type": "object",
            "properties": {
                "access": {
                    "$ref": "#/definitions/storage.AccessType"
                },
                "description": {
                    "type": "string"
                },
                "finish_time": {
                    "type": "string"
                },
                "max_team_cap": {
                    "type": "integer"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "registration_deadline": {
                    "type": "string"
                },
                "start_time": {
                    "type": "string"
                }
            }
        },
        "storage.UpdateTaskGroupRequest": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "tasks": {
                    "$ref": "#/definitions/storage.TasksBulkUpdateRequest"
                }
            }
        },
        "storage.UpdateTaskRequest": {
            "type": "object",
            "properties": {
                "correct_answers": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "group_id": {
                    "type": "string"
                },
                "hints": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "id": {
                    "type": "string"
                },
                "media_link": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "order_idx": {
                    "type": "integer"
                },
                "pub_time": {
                    "type": "string"
                },
                "question": {
                    "type": "string"
                },
                "reward": {
                    "type": "integer"
                },
                "verification": {
                    "$ref": "#/definitions/storage.VerificationType"
                }
            }
        },
        "storage.User": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "storage.VerificationType": {
            "type": "string",
            "enum": [
                "auto",
                "manual"
            ],
            "x-enum-varnames": [
                "VerificationAuto",
                "VerificationManual"
            ]
        },
        "taskgroups.GetResponse": {
            "type": "object",
            "properties": {
                "quest": {
                    "$ref": "#/definitions/storage.Quest"
                },
                "task_groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/storage.TaskGroup"
                    }
                }
            }
        },
        "teams.ChangeLeaderRequest": {
            "type": "object",
            "properties": {
                "new_captain_id": {
                    "type": "string"
                }
            }
        },
        "teams.CreateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "teams.UpdateRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "user.UpdatePasswordRequest": {
            "type": "object",
            "properties": {
                "new_password": {
                    "type": "string"
                },
                "old_password": {
                    "type": "string"
                }
            }
        },
        "user.UpdatePublicDataRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
