definitions:
  auth.GoogleOAuthRequest:
    properties:
      id_token:
        type: string
    type: object
  auth.Response:
    properties:
      access_token:
        type: string
      user:
        $ref: '#/definitions/storage.User'
    type: object
  auth.SignInRequest:
    properties:
      password:
        type: string
      username:
        type: string
    type: object
  storage.AccessType:
    enum:
    - public
    - link_only
    type: string
    x-enum-varnames:
    - Public
    - LinkOnly
  storage.CreateQuestRequest:
    properties:
      access:
        $ref: '#/definitions/storage.AccessType'
      description:
        type: string
      finish_time:
        type: string
      max_team_cap:
        type: integer
      media_link:
        type: string
      name:
        type: string
      registration_deadline:
        type: string
      start_time:
        type: string
    type: object
  storage.CreateTaskGroupRequest:
    properties:
      name:
        type: string
      order_idx:
        type: integer
      pub_time:
        type: string
    type: object
  storage.CreateUserRequest:
    properties:
      avatar_url:
        example: https://api.dicebear.com/7.x/thumbs/svg
        type: string
      password:
        example: "12345"
        type: string
      username:
        example: svayp11
        type: string
    type: object
  storage.DeleteTaskGroupRequest:
    properties:
      id:
        type: string
    type: object
  storage.Quest:
    properties:
      access:
        $ref: '#/definitions/storage.AccessType'
      creator:
        $ref: '#/definitions/storage.User'
      description:
        type: string
      finish_time:
        type: string
      id:
        type: string
      max_team_cap:
        type: integer
      media_link:
        type: string
      name:
        type: string
      registration_deadline:
        type: string
      start_time:
        type: string
      status:
        type: string
    type: object
  storage.TaskGroup:
    properties:
      id:
        type: string
      name:
        type: string
      orderIdx:
        type: integer
      pubTime:
        type: string
      quest:
        $ref: '#/definitions/storage.Quest'
    type: object
  storage.TaskGroupsBulkUpdateRequest:
    properties:
      create:
        items:
          $ref: '#/definitions/storage.CreateTaskGroupRequest'
        type: array
      delete:
        items:
          $ref: '#/definitions/storage.DeleteTaskGroupRequest'
        type: array
      update:
        items:
          $ref: '#/definitions/storage.UpdateTaskGroupRequest'
        type: array
    type: object
  storage.Team:
    properties:
      captain:
        $ref: '#/definitions/storage.User'
      id:
        type: string
      invite_link:
        type: string
      members:
        items:
          $ref: '#/definitions/storage.User'
        type: array
      name:
        type: string
      score:
        type: integer
    type: object
  storage.UpdateQuestRequest:
    properties:
      access:
        $ref: '#/definitions/storage.AccessType'
      creator_name:
        type: string
      description:
        type: string
      finish_time:
        type: string
      max_team_cap:
        type: integer
      media_link:
        type: string
      name:
        type: string
      registration_deadline:
        type: string
      start_time:
        type: string
    type: object
  storage.UpdateTaskGroupRequest:
    properties:
      id:
        type: string
      name:
        type: string
      order_idx:
        type: integer
      pub_time:
        type: string
    type: object
  storage.User:
    properties:
      avatar_url:
        type: string
      id:
        type: string
      username:
        type: string
    type: object
  teams.CreateRequest:
    properties:
      name:
        type: string
    type: object
  user.UpdatePasswordRequest:
    properties:
      new_password:
        type: string
      old_password:
        type: string
    type: object
  user.UpdatePublicDataRequest:
    properties:
      avatar_url:
        type: string
      username:
        type: string
    type: object
info:
  contact: {}
paths:
  /auth/google:
    post:
      parameters:
      - description: Google OAuth request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.GoogleOAuthRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Response'
        "400":
          description: Bad Request
        "415":
          description: Unsupported Media Type
      summary: Register new or sign in old user using Google OAuth2.0
  /auth/register:
    post:
      parameters:
      - description: Create user request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/storage.CreateUserRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Response'
        "400":
          description: Bad Request
        "415":
          description: Unsupported Media Type
      summary: Register new user and return auth data
  /auth/sign-in:
    post:
      parameters:
      - description: Sign in request
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/auth.SignInRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.Response'
        "400":
          description: Bad Request
        "403":
          description: Forbidden
        "415":
          description: Unsupported Media Type
      summary: Sign in to user account and return auth data
  /quest:
    post:
      parameters:
      - description: Main quest information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/storage.CreateQuestRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Quest'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "415":
          description: Unsupported Media Type
      summary: Create new quest
  /quest/{id}/task-groups/bulk:
    patch:
      parameters:
      - description: Requests to delete/create/update task groups
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/storage.TaskGroupsBulkUpdateRequest'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/storage.TaskGroup'
            type: array
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Patch task groups by creating new ones, delete, update and reorder
        all ones. Returns all exising task groups.
  /quest/{quest_id}:
    delete:
      parameters:
      - description: Quest ID
        in: path
        name: quest_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Delete quest
    get:
      parameters:
      - description: Quest ID
        in: path
        name: quest_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Quest'
        "404":
          description: Not Found
      summary: Get quest by id
    post:
      parameters:
      - description: Quest ID
        in: path
        name: quest_id
        required: true
        type: string
      - description: Quest information to update
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/storage.UpdateQuestRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Quest'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "415":
          description: Unsupported Media Type
      summary: Update main quest information
  /quest/{quest_id}/teams:
    post:
      parameters:
      - description: Desired team information
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/teams.CreateRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Team'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "406":
          description: Not Acceptable
      summary: Create new team
  /teams/join/{invite_path}:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.Team'
        "401":
          description: Unauthorized
        "406":
          description: Not Acceptable
      summary: Join team
  /user/{user_id}:
    delete:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
      summary: Delete user account
    get:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.User'
        "404":
          description: Not Found
      summary: Get user by id
    post:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Public data to set for user
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdatePublicDataRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.User'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
      summary: Update user public data such as username or avatar and returns new
        auth data
  /user/{user_id}/password:
    post:
      parameters:
      - description: User ID
        in: path
        name: user_id
        required: true
        type: string
      - description: Old and new password
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/user.UpdatePasswordRequest'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/storage.User'
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
      summary: Update user password
swagger: "2.0"
