version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - ENVIRONMENT=docker-dev
    tty: true
    build: .
    ports:
      - '8080:80'
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - questspace

  postgres:
    image: postgres:16.0
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    volumes:
      - ./internal/pgdb/migrations:/docker-entrypoint-initdb.d
    ports:
      - '1234:5432'
    networks:
      - questspace
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  questspace:
    driver: bridge