version: '3.9'
services:
  app:
    container_name: golang_container
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    tty: true
    build: .
    ports:
      - '8080:8080'
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgres
    networks:
      - questspace

  postgres:
    image: postgres:16.0
    container_name: postgres_container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=postgres
      - DATABASE_HOST=postgres
    volumes:
      - ./internal/pgdb/migrations:/docker-entrypoint-initdb.d
    ports:
      - '1234:5432'
    networks:
      - questspace

networks:
  questspace:
    driver: bridge