apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: questspace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: questspace-backend
  template:
    metadata:
      labels:
        app: questspace-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: backend-container
          image: __VERSION__
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
          env:
            - name: ENVIRONMENT
              value: prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: questspace-db-secret
                  key: questspace-postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: questspace-db-secret
                  key: questspace-postgres-password
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: questspace-jwt-secret
                  key: jwt-secret-key
            - name: GOOGLE_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: questspace-google-secret
                  key: google-oauth-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: questspace
spec:
  selector:
    app: questspace-backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080