apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: questspace-db-secret
# NOTE: Values should be base64-encoded
# P.S. Obviously not the real credentials
data:
  questspace-postgres-user: cG9wYSB2ZXN0b3Y=
  questspace-postgres-password: b2gsIG15IGZhdm91cml0ZSBhYnN0cmFjdGlvbiBvZiBrOHMgLSBlbXBsb3ltZW50