apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: questspace-backend
  template:
    metadata:
      labels:
        app: questspace-backend
    spec:
      imagePullSecrets:
        - name: docker-registry-secret
      containers:
        - name: backend-container
          image: cr.yandex/crpl9s9mvc8h74r32rk4/backend:0.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ENVIRONMENT
              value: prod
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: questspace-db-secret
                  key: questspace-postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: questspace-db-secret
                  key: questspace-postgres-password
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: questspace-backend
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
      nodePort: 31337