name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-22.04
    container:
      image: golang:1.20.10-alpine
    steps:
    - uses: actions/checkout@v4

    - name: Build
      run: go build -v ./...
      working-directory: ./src/

    - name: Test
      run: go test -v ./...
      working-directory: ./src/

  lint:
    runs-on: ubuntu-22.04
    container:
      image: cytopia/goimports:latest
    steps:
    - uses: actions/checkout@v4

    - name: Check style
      run: goimports -local 'questspace/' -d -e ./src