name: pgmigrate
on: workflow_dispatch

jobs:
  pgmigrate:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - run: mkdir -p ~/.postgresql/ && echo -n '${{ vars.CA_CERTS }}' > ~/.postgresql/root.crt

      - name: Install pgmigrate
        run: pip install yandex-pgmigrate

      - name: Apply migrations to database
        working-directory: ./src/internal/pgdb
        env:
          PGHOST: ${{ vars.POSTGRES_HOST }}
          PGPORT: ${{ vars.POSTGRES_PORT }}
          PGDATABASE: ${{ vars.POSTGRES_DATABASE }}
          PGUSER: ${{ secrets.POSTGRES_USER }}
          PGPASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        run: pgmigrate -c "sslmode=verify-full target_session_attrs=read-write" -v -t latest migrate
